### ISSUE TITLE
`ProviderError: Unknown error` when using BitBucket

### ISSUE THREAD

**Issue by daniel-liuzzi** [maximilianschmitt/gitclick#5]
After adding a BitBucket account, issuing `gitclick create` shows the following error:

```
~\> gitclick create

~\AppData\Roaming\npm\node_modules\gitclick\es5\bin\cli.js:231
    throw err;
          ^
ProviderError: Unknown error
    at ~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\lib\api.js:42:11
    at tryCatch1 (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\util.js:63:19)
    at Promise$_callHandler [as _callHandler] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\async.js:74:12)
    at Async$consumeFunctionBuffer (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\async.js:37:14)
    at process._tickCallback (node.js:442:13)
```

This was reproduced on both Windows 8.1 Pro and on a Docker image running Ubuntu.

As an aside, running the same `gitclick create` command against GitHub works as expected.

**Comment by maximilianschmitt** [comment]
Have you checked if your Bitbucket credentials are correct and if a repository with the same name doesn't already exist on your account? What is the name of the folder you are running the command from?

**Comment by daniel-liuzzi** [comment]
I always paste my credentials from KeePass; I never type them directly, so I doubt that's the problem. Just to be sure, I went and tried logging into bitbucket.com using those same credentials and it worked fine, so my credentials seem correct.

Regarding the folder I ran the command from, I honestly don't remember, but I went and created a brand new local repository using a name I know for a fact it does not already exist on my BitBucket account. Then I tried `gitclick create` again. It gave me an error which, oddly enough, was different this time around:

```
~\Desktop\mytestrepo> gitclick add
? Choose a name: BitBucket
? Where is your account hosted? Bitbucket
? Bitbucket Username or E-Mail: dliuzzi@gmail.com
? Bitbucket Password: ********************
Account 'BitBucket' added.
~\Desktop\mytestrepo> touch README.md
~\Desktop\mytestrepo> e .
~\Desktop\mytestrepo> git init
Initialized empty Git repository in C:/Users/Daniel/Desktop/mytestrepo/.git/
~\Desktop\mytestrepo [master +1 ~0 -0 !]> gs
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        README.md

nothing added to commit but untracked files present (use "git add" to track)
~\Desktop\mytestrepo [master +1 ~0 -0 !]> ga .
~\Desktop\mytestrepo [master +1 ~0 -0]> git commit -m 'Initial commit'
[master (root-commit) 2e3e6f8] Initial commit
 1 file changed, 1 insertion(+)
 create mode 100644 README.md
~\Desktop\mytestrepo [master]> gitclick create

~\AppData\Roaming\npm\node_modules\gitclick\es5\bin\cli.js:231
    throw err;
          ^
ProviderError: Bad request
    at ~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\lib\api.js:42:11
    at tryCatch1 (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\util.js:63:19)
    at Promise$_callHandler [as _callHandler] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\async.js:74:12)
    at Async$consumeFunctionBuffer (~\AppData\Roaming\npm\node_modules\gitclick\node_modules\gitclick-provider-bitbucket\node_modules\bluebird\js\main\async.js:37:14)
    at process._tickCallback (node.js:442:13)
~\Desktop\mytestrepo [master]>
```

**Comment by maximilianschmitt** [comment]
Hey Daniel, I was trying to reproduce your error and also got a ProviderError when using Bitbucket. I discovered that using my email address to authenticate does not work. Please try using your Bitbucket username. Sorry that the prompt says "Username or e-mail" but e-mails don't seem to work with the Bitbucket API.

**Comment by maximilianschmitt** [comment]
I've also now updated the prompt when adding a Bitbucket account to reflect this issue (in `0.4.10`).

**Comment by daniel-liuzzi** [comment]
Hey Max.

Thanks for your response. Using my username instead of the email worked perfectly. I have no idea what is BitBucket's reasoning on this API decision, but anyway, I'm glad it works.

If you allow me a small suggestion, I would recommend validating the credentials when doing `gitclick add`, and ask users to re-enter them if authentication fails. I have tried adding accounts with gibberish information on GitHub and BitBucket, and they both worked:

```
~\Desktop\mytestrepo [master]> gitclick add
? Choose a name: jklsdg
? Where is your account hosted? Bitbucket
? Bitbucket Username (E-Mail does NOT work!) lksgfjsgflkdjsgfdlksdgf
? Bitbucket Password: ************************
Account 'jklsdg' added.

~\Desktop\mytestrepo [master]> gitclick add
? Choose a name: slkfjdsgf
? Where is your account hosted? GitHub
? GitHub Username or E-Mail: lsdfkjdsgflkjsdgf
? GitHub Password or Access Token: ***************************
Account 'slkfjdsgf' added.
```

Validating credentials on input is a standard practice, as it informs users of their mistake _right after making the mistake_ as opposed to later. I believe showing errors in this manner seems a more intuitive approach, because otherwise users might tend to think the problem is with `gitclick create` (as that's what they ran last), instead of `gitclick add`.

Thanks again.

**Comment by maximilianschmitt** [comment]
Hey Daniel, I'm glad you got it working. I agree with you that validating the credentials would be nice. I think that might be up next on my todo list. :) Thanks again for helping make gitclick a better tool. Let me know anytime if you need anything.
